name: altcamplive CI/CD

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
            
jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2
        - run:
            npm i
        - run:
            npm run build
            cd ..
            pm2 stop 0
            pm2 start 0
            pm2 save
            sudo service nginx restart
