name: altcamplive CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            
jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2
        - run:
            npm install
        - run:
            npm run build
