name: altcamplive CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: "Create env file"
        run: |
            touch .env
            echo VITE_TINY_KEY=${{ secrets.VITE_TINY_KEY }} >> .env
            echo VITE_GA_ID=${{ secrets.VITE_GA_ID }} >> .env
            echo VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} >> .env
      - name: "Install dependencies"
        run: |
            export NODE_OPTIONS=–max-old-space-size=2048
            npm install
      - name: "Build"
        run: |
            npm run build
      - name: "Install PM2"
        run: |
            pm2 stop 0
            pm2 start 0
            pm2 save
            sudo service nginx restart
