name: CI/CD to DigitalOcean Droplet

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.19.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: altcamp
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            cd /var/www/altcampfrontend/_work/altcampv1-frontend/altcampv1-frontend
            git pull origin dev
            npm ci
            npm run build
            sudo systemctl restart your-app-service
