name: Deploy App
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy to droplet
        uses: digitalocean/action-droplet@v2
        with:
          droplet_name: ${{ secrets.DROPLET_USERNAME }}
          ssh_key_id: ${{ secrets.SSH_PRIVATE_KEY }}
          region: default-fra1
          image: "ubuntu-20.04"
          size: "s-1vcpu-1gb"
          action: "create"
          wait: true
          commands:
            - run: echo "Installing nginx..."
            - run: apt-get update
            - run: apt-get install -y nginx
            - run: echo "Copying React app to /var/www/html..."
            - run: rsync -a ./build/ /var/www/html
            - run: echo "Restarting nginx..."
            - run: service nginx restart
