name: CI/CD for React App

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy to Droplet
        uses: digitalocean/action-droplet@v2
        with:
          droplet_name: altcamp
          region: us-west-2
          image: ubuntu-20.04
          ssh_key: ${{ secrets.DROPLET_SSH_KEY }}
          files:
            - build/:/var/www/altcampfrontend/_work/altcampv1-frontend/altcampv1-frontend
    finally:
      - name: Clean up
        run: |
          sudo rm -rf build
